import React from "react";
import { Container, Row, Col } from "react-bootstrap";
const About = () => {
  return (
    <>
      <Container style={{ marginTop: "50px" }}>
        <h1>Qui sommes-nous ?</h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur voluptate ratione sed voluptates labore magnam tempora dolorem consequatur eum dolores, vel sunt, quidem nisi in repellat quibusdam accusantium. Sint architecto vel debitis sed accusantium porro tenetur est odit voluptatum esse quaerat error id, ea quasi assumenda eius unde ad possimus rerum perspiciatis iste? Velit aspernatur commodi id, quos dolores magnam nulla hic pariatur necessitatibus, dolore maiores! Necessitatibus aliquid quaerat fugiat vero temporibus perferendis expedita labore explicabo porro maiores, ullam ipsam quia inventore repellat asperiores consequuntur soluta pariatur ipsum vitae minus. Dolorem provident consectetur totam iusto, possimus quod magni quas dolores minima qui voluptatem recusandae cupiditate! Atque libero ab explicabo, nobis inventore pariatur nihil placeat! Praesentium, officiis? Atque natus tenetur quos fugiat similique! Animi, sequi aut. Beatae deserunt culpa nam quam autem, sint asperiores nostrum facere magni quae dolore ab eum nesciunt ex sit delectus soluta minus error sapiente aliquam! Quidem repellendus, illo pariatur ad eius neque quis assumenda labore soluta numquam aliquam at adipisci, ratione repudiandae? Nisi reprehenderit aspernatur maxime modi, neque, rem excepturi natus, distinctio aliquam iure qui. Similique, dolor! Aspernatur voluptates dolores magnam quas! Libero accusamus aliquid, aliquam saepe commodi dignissimos nobis dolores deleniti at et illum quo.</p>
        <h1>Notre spécialité</h1>
        <Row>
          <Col md={6}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, autem quibusdam! Et eligendi reprehenderit earum beatae, odio dolores officia porro recusandae asperiores tenetur, exercitationem voluptas ipsa saepe? Sunt placeat in eaque id. Laudantium inventore qui distinctio itaque delectus facilis, nihil, incidunt nemo consequuntur praesentium dolorum earum mollitia consectetur consequatur aperiam similique quis? Voluptatibus possimus tempore debitis adipisci beatae, sint id? Inventore placeat exercitationem sit doloribus eius necessitatibus enim provident error. In earum mollitia, itaque quidem enim non accusamus recusandae at omnis cumque harum suscipit cum sapiente tempora magnam, modi tenetur veritatis id rerum cupiditate, voluptate placeat! Labore reprehenderit possimus deleniti necessitatibus, mollitia alias sequi, cum, ipsum veritatis quod veniam facere. Deserunt, quae placeat, aspernatur tempora debitis cupiditate inventore totam adipisci voluptatem, earum expedita magni corporis tenetur. Saepe, maxime magni! Veritatis incidunt soluta laboriosam! Necessitatibus voluptatem quo quasi nihil aperiam! Odio voluptate nam expedita maxime corporis numquam voluptatum voluptatem sapiente quia unde, asperiores dolore! Vitae modi quam iste consequuntur aliquam deserunt dolores, placeat iusto minus perspiciatis facere dignissimos officia maiores! Nobis saepe alias sit quam natus rem quas, architecto nam eaque esse quidem eius. Ipsa veritatis saepe deserunt adipisci quia, doloribus minus maiores in obcaecati fugit laboriosam nobis veniam sequi! Doloremque?</p>
          </Col>
          <Col md={6}>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloribus odit nemo porro inventore recusandae dolores unde laboriosam dignissimos voluptates. Distinctio dolorem consequuntur voluptatum fugiat quibusdam, harum, tenetur veniam temporibus provident sequi dolores cupiditate culpa nam eius optio obcaecati quisquam maxime expedita, maiores illum. Vitae suscipit libero asperiores voluptate non, officia cupiditate nobis a quia eos. Repellendus ab error vel vitae praesentium temporibus alias harum iure inventore soluta, eveniet, deleniti dolorum accusantium. Quae nam cum harum architecto, voluptates incidunt possimus perferendis minus dicta magni obcaecati ea iste quo tempore facere ullam laboriosam placeat accusamus culpa, magnam officia. Velit, delectus! Iste, placeat exercitationem quisquam voluptatum voluptate maiores laboriosam consequatur dolor praesentium cumque nisi officia accusamus. Officia eligendi, corrupti similique ea, deserunt amet a quo laboriosam, optio soluta quaerat? Enim assumenda, animi nisi impedit tempore asperiores culpa debitis error dicta qui quae facilis officia hic quos laudantium iure iste aliquid magnam totam tempora dolorum explicabo repudiandae saepe ducimus. Unde vero, minus et neque maiores mollitia voluptatibus qui nobis deleniti eveniet aperiam magni! Reiciendis non possimus, ratione suscipit ullam repellat voluptatum eum earum ab autem rem obcaecati qui dolor maxime odio quidem vitae vero minus. Iste repudiandae ipsam dolor consequuntur dignissimos ipsum, maxime itaque?</p>
          </Col>
        </Row>
        <Row>
          <h1>Le Chef</h1>
          <Col md={3}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, deserunt ipsam repellat necessitatibus labore tempore aliquam ab ex sed, laborum qui placeat deleniti ducimus ea perspiciatis vero. Aliquid excepturi placeat rem pariatur eos ipsam corrupti. Corrupti deleniti, rerum quibusdam nihil officiis numquam consectetur non harum exercitationem. Unde voluptate nemo totam laudantium inventore, veniam eligendi dolorum velit cum suscipit, amet ut molestias asperiores nam aliquam facere corrupti ratione rerum, dolore illo accusantium non eaque! Obcaecati, officiis culpa esse blanditiis ipsa voluptas dicta! Quod beatae delectus molestiae, nemo fugiat, temporibus minus reiciendis ea unde fuga aut est! Deserunt in ab repudiandae iste.</p>
          </Col>
          <Col md={3}>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Asperiores quidem ex praesentium porro blanditiis quis totam, natus doloremque fugiat eum, tempore voluptatum perspiciatis at eligendi, eveniet animi ratione. Quis quidem maiores vero illum soluta molestias earum corrupti nemo quia veniam. Eaque mollitia natus architecto ab facere pariatur, doloribus libero aut, reprehenderit minus in recusandae optio laborum adipisci dolorum vero sequi praesentium explicabo. Libero minima odit impedit consequatur, enim aspernatur laboriosam! Corporis facilis alias iure impedit repellendus corrupti perspiciatis? Officia facere reiciendis porro cumque! Ea fugit, nam et asperiores culpa, natus eius non voluptas neque exercitationem repudiandae delectus sunt officia error.</p>
          </Col>
          <Col md={3}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non corrupti natus doloremque corporis sequi laborum dolores perspiciatis dolore neque accusantium unde, magni minus! Sint sed illo nihil at similique! Porro iste impedit, quibusdam repudiandae tenetur nulla omnis pariatur enim beatae atque vel perferendis itaque magnam iure cupiditate tempora fugit, cumque aperiam reprehenderit dolorum natus corporis! Quo quaerat doloremque vero vitae recusandae accusamus mollitia odit maiores quisquam expedita, hic quia distinctio asperiores debitis esse quae porro obcaecati aperiam. Veritatis et, optio sapiente incidunt quam ut corrupti fugit autem enim illum aliquam nulla laboriosam dolorum dolorem eum magnam deleniti aspernatur, ex soluta.</p>
          </Col>
          <Col md={3}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto perspiciatis eius labore repellendus optio officia laudantium iste natus delectus aperiam. Vero similique consectetur cum, et adipisci dolorum quia esse aperiam minus sunt blanditiis vel illo aliquam exercitationem officia dignissimos, placeat quasi repudiandae quisquam. Et doloremque qui nesciunt, repudiandae perferendis vero id voluptatem voluptates quisquam sunt tempore dolores, modi nisi architecto expedita suscipit ipsam a velit esse earum non odit placeat est! Quae laboriosam pariatur natus dolore placeat, hic ab aliquid vero saepe ut facilis repellat est suscipit eius, repudiandae mollitia voluptatem veritatis recusandae magni sunt, voluptate aut beatae! Nisi, voluptates.</p>
          </Col>
        </Row>
      </Container>
    </>
  );
};

export default About;
